<?php

/**
 * @file
 * Primary module hooks for interactive_event_calendar module.
 */

/**
* Implements hook_views_pre_render().
*/
function interactive_event_calendar_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'events_calendar')) {
    $view->element['#attached']['library'][] = 'interactive_event_calendar/interactive_event_calendar';
  }
  
}

function interactive_event_calendar_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'interactive_event_calendar/interactive_event_calendar';
}

