<?php

/**
 * @file
 * Primary module hooks for dynamic calendar slides module.
 */

 /**
 * Implements hook_fullcalendar_view_alter().
 */
function dynamic_calendar_slides_fullcalendar_view_alter(array &$view, array &$fullcalendar_settings) {
  // Replace with your view ID and block machine name.
  if ($view['id'] === 'brand_events') {
    $view['#attached']['library'][] = 'dynamic_calendar_slides/dynamic_calendar_slides.fullcalendar_interaction';
  }
}

